env:
    MANIFEST: https://github.com/PixelExperience/manifest.git -b thirteen
    DEVICE: r5x
    OEM: realme
    DT_LINK: https://github.com/eartinity/device_realme_r5x.git
    DT_BRANCH: pe
    DT_PATH: device/$OEM/$DEVICE
    VT_LINK: https://github.com/eartinity/vendor_realme_r5x.git
    VT_BRANCH: thirteen 
    VT_PATH: vendor/$OEM/$DEVICE
    KT_LINK: https://github.com/eartinity/kernel_realme_trinket.git
    KT_BRANCH: labs-dynamic
    PLATFORM: sm6125
    KT_PATH: kernel/$OEM/$DEVICE
    TARGET: vndk
    EXTRA_CMD: export BUILD_BROKEN_MISSING_REQUIRED_MODULES=true
    LUNCH_COMBO: aosp_$DEVICE-userdebug
    OUTPUT: PixelExperience*.zip

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G



  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h

  Setup-Environment_script:
      - sudo apt update &&sudo apt install pigz wget jq curl repo -y 
      - sudo apt upgrade -y

  Sync_script:
      - mkdir -p ~/work
      - cd ~/work
      - git config --global user.email "pranavjha21@noreply.github.com"
      - git config --global user.name "pranavjha21"
      - repo init --depth=1 -u $MANIFEST
      - repo sync -j4 --force-sync --no-tags --no-clone-bundle
      - git clone $DT_LINK -b $DT_BRANCH $DT_PATH
      - git clone $VT_LINK -b $VT_BRANCH $VT_PATH
      - git clone $KT_LINK -b $KT_BRANCH $KT_PATH

  Post-Storage-Checker_script:
      - df -h

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - . build/envsetup.sh
      - lunch $LUNCH_COMBO
      - export USE_CCACHE=1
      - export CCACHE_DIR=/tmp/ccache
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1
      - ccache -M 50G
      - ccache -o compression=true
      - ccache -o compression=true
      - ccache -z
      - $EXTRA_CMD
      - mka $TARGET

  Upload_script:
      - cd /tmp
      - time tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1 ccache 1
      - cd /tmp/ccache
      - curl --upload-file ./ccache.tar.gz https://transfer.sh/ccache.tar.gz
  
